name: github action demo pipeline
on:
   push:
       branches:
         -main

jobs:
    demo-job:
           runs-on: ubuntu-latest
           steps:
               -name: checkout code
               uses: actions/checkout@v2

               -name: print message
               runs: echo 'Welcome to Github Actions'